on: [pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        plan:
          - node-version: "20.4.0"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.plan.node-version }}
          cache: "npm"
          cache-dependency-path: ./yarn.lock
      - name: Install dependencies
        run: npm install
      - name: Lint & Type check
        run: npm run lint && npm run type-check
      - name: Build
        run: npm run build && npm run export
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}-out
          path: out
